### ISSUE TITLE
[ToDo] Make repo pip installable

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/seidemann-lab-to-nwb#1]

**Comment by h-mayorquin** [comment]
@CodyCBakerPhD 
What do you mean here? create a conda environment? The package can be installed by pip as it is. Could you remind me? I was looking in my notes and could not find this.

**Comment by CodyCBakerPhD** [comment]
Proper `/src/seidemann_lab_to_nwb/ophys_dataset` package structure

**Comment by CodyCBakerPhD** [comment]
Also proper naming... the current name in `setup` does not correspond
