### ISSUE TITLE
[ToDo] Ophys: synchronize and convert with TiffImagingInterface

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/seidemann-lab-to-nwb#4]
May require some modifications to the TiffImagingExtractor to operate on their binary blob data.

Also need to figure out how to get the sampling frequency.

Most difficult thing will be parsing their synchronization channels in the `.h5` file, which counted 304 different frames than the image files report.

**Comment by h-mayorquin** [comment]
I think this is done now with the creation of the interface in the current conversion?
